---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      babel:
        patterns:
          - '@babel/*'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
