version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run:
          name: Yarn
          command: "yarn install"
      - run:
          name: Test Build
          command: "make build"
  publish:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run:
          name: Yarn
          command: "yarn install"
      - run:
          name: Build Prod
          command: "make build_prod"
      - run:
          name: publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" >> ~/.npmrc
            npm publish --access public

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - publish:
          context:
            - retracedhq
          filters:
            branches:
              only: release
